### ISSUE TITLE
Hello-World (CAU-client)

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#104]
Make CAU client work with the hello-world test

**Comment by syc17** [comment]
I think this issue should really be 'Hello-World (CAU and CAU-client).  The CAU-client is dumb, the issues we have seen so far have been about obsolete trust certificates, CAU unable to connect to CA etc.  Therefore, we need to look at CAU and CAU-client as a unit.  And UPC is responsible for CAU, so I am adding Sarang to this task.

**Comment by fcarp10** [comment]
We skip for now CAU for f2f demo. No updates since the last demo in Brussels.
