### ISSUE TITLE
Hello-World (identification)

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#107]
Define how to show Identification functionality for hello-world test

**Comment by syc17** [comment]
May I ask if you intend to use device ID or something else for identification?  It would be good if we could map the certificate to something meaningful to capture fog membership (eg. CN=agentID, O=FogCluster......)  But please note that CN is constrained to 64 char length and deviceID is more than 64 length.

**Comment by fcarp10** [comment]
We skip for now Identification for f2f demo. No updates since the last demo in Brussels.

**Comment by ALEJANDROJ19** [comment]
Tested and working without any issue.

Last stable version: mf2c/identification:1.0
