### ISSUE TITLE
Hello-World (Policies)

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#108]
Define how to show Policies functionality for hello-world test

**Comment by fcarp10** [comment]
We skip for now Policies for f2f demo. No updates since the last demo in Brussels.

**Comment by ALEJANDROJ19** [comment]
Last stable and tested version of Policies: [mf2c/policies:0.1.7b](https://cloud.docker.com/u/mf2c/repository/docker/mf2c/policies/tags)

Known issues (Doesn't affect the integration):

- When Discovery is not configured correctly, FCJP submodule inside policies enters into an infinite loop.
- Some triggers are working, but the summary reports some errors, due bad protocol implementation in the modules.

I also added a new endpoint (https://localhost/rm/components) to check the status of the resource management components.
