### ISSUE TITLE
Hello-world (Dataclay/CIMI)

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#110]
CIMI returns 405 when submitting a device:

{
    "deviceID": "123",
    "isLeader": false,
    "os": "Linux-4.13.0-38-generic-x86_64-with-debian-8.10",
    "arch": "x86_64",
    "cpuManufacturer": "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz",
    "physicalCores": 4,
    "logicalCores": 8,
    "cpuClockSpeed": "1.8000 GHz",
    "memory": 7874.2109375,
    "storage": 234549.5078125,
    "powerPlugged": true,
    "networkingStandards": "['eth0', 'lo']",
    "ethernetAddress": "[snic(family=<AddressFamily.AF_INET: 2>, address='192.168.1.3', netmask='255.255.255.0', broadcast='192.168.1.255', ptp=None), snic(family=<AddressFamily.AF_PACKET: 17>, address='02:42:ac:11:00:03', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]",
    "wifiAddress": "Empty",
    "agentType": "normal",
    "actuatorInfo": "test"
}

**Comment by cjdcordeiro** [comment]
hi, this is not going to be fixed I believe, cause the proxy has been discontinued

**Comment by cjdcordeiro** [comment]
if I remember, it was a mismatch between the schemas in DC and CIMI, which can only be fixed by @ssgUPC

**Comment by aqueralt** [comment]
I cannot find where the error is... The device resource spec here:
https://github.com/mF2C/cimi/blob/master/server/src/com/sixsq/slipstream/ssclj/resources/spec/device.cljc
matches with the model in dataClay. Also, this json provided by Fran can be inserted in dataClay without going through the proxy. So, the problem seems to be in the CIMI-dataClay integration, on which SixSq are currently working.

**Comment by ssgUPC** [comment]
Dear @cjdcordeiro, I think before I went for the vacation, I solved the issues...which are regarding my components... and then I tested with other resource management components (i.e., policy block) and it was working... Regarding the issue of CIMI specs and dataclay classes which are related to my resource-categorization component - what I can inform you that, I have already fixed these issues...

**Comment by cjdcordeiro** [comment]
please paste here the logs from dcproxy when you execute that command

**Comment by fcarp10** [comment]
Now I see that is not only the device, it happens with all resources. I see some errors on DCproxy:

dcproxy_1          | [Wed Jan 30 16:30:02 UTC 2019] *** DataService DS1 for language java is ready
dcproxy_1          | 
dcproxy_1          | [dClayTool] 7d20c083-f2b3-48f3-9c23-ef1565df25c2
dcproxy_1          | 
dcproxy_1          | [dClayTool] User mf2c registered in data model of namespace: CimiNS with contract ID: 
dcproxy_1          | 77bb0914-2862-4e7b-8096-17387f9efbd3
dcproxy_1          | 
dcproxy_1          | [dClayTool] Stubs stored in: stubs
dcproxy_1          | 
dcproxy_1          | Compiling ...  done
dcproxy_1          | Jan 30, 2019 4:30:18 PM com.sixsq.dataclay.proxy invoke
dcproxy_1          | INFO: initializing dataclay
dcproxy_1          | Jan 30, 2019 4:30:20 PM com.sixsq.dataclay.proxy invoke
dcproxy_1          | INFO: initializing DataClayWrapper
dcproxy_1          | Cannot create property=implementations for JavaBean=!!dataclay.util.management.stubs.StubInfo
dcproxy_1          | applicantID: !!dataclay.util.ids.AccountID 'e32e94d0-9059-4a93-a1d1-6f1cfa53a06a'
dcproxy_1          | classID: !!dataclay.util.ids.MetaClassID '326e6079-90b4-483b-b09d-1019a98f9b20'
dcproxy_1          | className: CIMI.ResourceCollection
dcproxy_1          | contracts: !!set {!!dataclay.util.ids.ContractID '77bb0914-2862-4e7b-8096-17387f9efbd3': null}
dcproxy_1          | implementations: null
dcproxy_1          | implementationsByID: null
dcproxy_1          | namespace: null
dcproxy_1          | namespaceID: null
dcproxy_1          | parentClassName: null
dcproxy_1          | properties: null
dcproxy_1          | propertyListWithNulls: null
dcproxy_1          | 
dcproxy_1          |  in 'reader', line 1, column 1:
dcproxy_1          |     !!dataclay.util.management.stubs ... 
dcproxy_1          |     ^
dcproxy_1          | Cannot create property=params for JavaBean=dataclay.util.management.stubs.ImplementationStubInfo@15853324
dcproxy_1          |  in 'reader', line 7, column 32:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id001 !!dataclay.util.managemen ... 
dcproxy_1          |                                    ^
dcproxy_1          | Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          |  in 'reader', line 17, column 7:
dcproxy_1          |           param0: !!dataclay.util.manageme ... 
dcproxy_1          |           ^
dcproxy_1          | 
dcproxy_1          |  in 'reader', line 7, column 3:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id ... 
dcproxy_1          |       ^
dcproxy_1          | 
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
dcproxy_1          | 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
dcproxy_1          | 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
dcproxy_1          | 	at dataclay.DataClayObject.getStubInfoFromClass(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.getStubInfo(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.getMetaClassID(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.ObjectWithDataParamOrReturn.<init>(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.DataClaySerializationLib.serializeDataClayObjectWithData(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.DataClaySerializationLib.serializeParamsOrReturn(Unknown Source)
dcproxy_1          | 	at dataclay.commonruntime.ClientRuntime.serializeMakePersistent(Unknown Source)
dcproxy_1          | 	at dataclay.commonruntime.ClientRuntime.makePersistent(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.makePersistent(Unknown Source)
dcproxy_1          | 	at api.DataClayWrapper.createLocalResourceCollections(DataClayWrapper.java:86)
dcproxy_1          | 	at api.DataClayWrapper.init(DataClayWrapper.java:71)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main$fn__1029.invoke(proxy.clj:39)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main.invokeStatic(proxy.clj:37)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main.doInvoke(proxy.clj:28)
dcproxy_1          | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
dcproxy_1          | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
dcproxy_1          | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
dcproxy_1          | 	at com.sixsq.dataclay.proxy.main(Unknown Source)
dcproxy_1          | Caused by: Cannot create property=params for JavaBean=dataclay.util.management.stubs.ImplementationStubInfo@15853324
dcproxy_1          |  in 'reader', line 7, column 32:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id001 !!dataclay.util.managemen ... 
dcproxy_1          |                                    ^
dcproxy_1          | Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          |  in 'reader', line 17, column 7:
dcproxy_1          |           param0: !!dataclay.util.manageme ... 
dcproxy_1          |           ^
dcproxy_1          | 
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247)
dcproxy_1          | 	... 26 more
dcproxy_1          | Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          | 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
dcproxy_1          | 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:285)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:209)
dcproxy_1          | 	... 37 more
dcproxy_1          | Cannot create property=implementations for JavaBean=!!dataclay.util.management.stubs.StubInfo
dcproxy_1          | applicantID: !!dataclay.util.ids.AccountID 'e32e94d0-9059-4a93-a1d1-6f1cfa53a06a'
dcproxy_1          | classID: !!dataclay.util.ids.MetaClassID '326e6079-90b4-483b-b09d-1019a98f9b20'
dcproxy_1          | className: CIMI.ResourceCollection
dcproxy_1          | contracts: !!set {!!dataclay.util.ids.ContractID '77bb0914-2862-4e7b-8096-17387f9efbd3': null}
dcproxy_1          | implementations: null
dcproxy_1          | implementationsByID: null
dcproxy_1          | namespace: null
dcproxy_1          | namespaceID: null
dcproxy_1          | parentClassName: null
dcproxy_1          | properties: null
dcproxy_1          | propertyListWithNulls: null
dcproxy_1          | 
dcproxy_1          |  in 'reader', line 1, column 1:
dcproxy_1          |     !!dataclay.util.management.stubs ... 
dcproxy_1          |     ^
dcproxy_1          | Cannot create property=params for JavaBean=dataclay.util.management.stubs.ImplementationStubInfo@15853324
dcproxy_1          |  in 'reader', line 7, column 32:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id001 !!dataclay.util.managemen ... 
dcproxy_1          |                                    ^
dcproxy_1          | Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          |  in 'reader', line 17, column 7:
dcproxy_1          |           param0: !!dataclay.util.manageme ... 
dcproxy_1          |           ^
dcproxy_1          | 
dcproxy_1          |  in 'reader', line 7, column 3:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id ... 
dcproxy_1          |       ^
dcproxy_1          | 
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
dcproxy_1          | 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
dcproxy_1          | 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
dcproxy_1          | 	at dataclay.DataClayObject.getStubInfoFromClass(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.getStubInfo(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.getMetaClassID(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.SerializationLibUtils.createMetaData(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.ObjectWithDataParamOrReturn.serialize(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.DataClaySerializationLib.createBufferAndSerialize(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.DataClaySerializationLib.serializeDataClayObjectWithData(Unknown Source)
dcproxy_1          | 	at dataclay.serialization.lib.DataClaySerializationLib.serializeParamsOrReturn(Unknown Source)
dcproxy_1          | 	at dataclay.commonruntime.ClientRuntime.serializeMakePersistent(Unknown Source)
dcproxy_1          | 	at dataclay.commonruntime.ClientRuntime.makePersistent(Unknown Source)
dcproxy_1          | 	at dataclay.DataClayObject.makePersistent(Unknown Source)
dcproxy_1          | 	at api.DataClayWrapper.createLocalResourceCollections(DataClayWrapper.java:86)
dcproxy_1          | 	at api.DataClayWrapper.init(DataClayWrapper.java:71)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main$fn__1029.invoke(proxy.clj:39)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main.invokeStatic(proxy.clj:37)
dcproxy_1          | 	at com.sixsq.dataclay.proxy$_main.doInvoke(proxy.clj:28)
dcproxy_1          | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
dcproxy_1          | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
dcproxy_1          | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
dcproxy_1          | 	at com.sixsq.dataclay.proxy.main(Unknown Source)
dcproxy_1          | Caused by: Cannot create property=params for JavaBean=dataclay.util.management.stubs.ImplementationStubInfo@15853324
dcproxy_1          |  in 'reader', line 7, column 32:
dcproxy_1          |       delete(Ljava/lang/String;)V: &id001 !!dataclay.util.managemen ... 
dcproxy_1          |                                    ^
dcproxy_1          | Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          |  in 'reader', line 17, column 7:
dcproxy_1          |           param0: !!dataclay.util.manageme ... 
dcproxy_1          |           ^
dcproxy_1          | 
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:268)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247)
dcproxy_1          | 	... 28 more
dcproxy_1          | Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'params' on class: dataclay.util.management.stubs.ImplementationStubInfo
dcproxy_1          | 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:189)
dcproxy_1          | 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:178)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:285)
dcproxy_1          | 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:209)
dcproxy_1          | 	... 39 more
dcproxy_1          | Jan 30, 2019 4:30:20 PM io.grpc.internal.ProxyDetectorImpl detectProxy
dcproxy_1          | WARNING: Failed to construct URI for proxy lookup, proceeding without proxy
dcproxy_1          | java.net.URISyntaxException: Illegal character in hostname at index 26: https://docker-compose-it2_ds1java1_1.docker-compose-it2_default:2127
dcproxy_1          | 	at java.net.URI$Parser.fail(URI.java:2848)
dcproxy_1          | 	at java.net.URI$Parser.parseHostname(URI.java:3387)
dcproxy_1          | 	at java.net.URI$Parser.parseServer(URI.java:3236)
dcproxy_1          | 	at java.net.URI$Parser.parseAuthority(URI.java:3155)
dcproxy_1          | 	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
dcproxy_1          | 	at java.net.URI$Parser.parse(URI.java:3053)
dcproxy_1          | 	at java.net.URI.<init>(URI.java:673)
dcproxy_1          | 	at io.grpc.internal.ProxyDetectorImpl.detectProxy(ProxyDetectorImpl.java:128)
dcproxy_1          | 	at io.grpc.internal.ProxyDetectorImpl.proxyFor(ProxyDetectorImpl.java:118)
dcproxy_1          | 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:207)
dcproxy_1          | 	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:188)
dcproxy_1          | 	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1130)
dcproxy_1          | 	at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:79)
dcproxy_1          | 	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1032)
dcproxy_1          | 	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73)
dcproxy_1          | 	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:1000)
dcproxy_1          | 	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1044)
dcproxy_1          | 	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:201)
dcproxy_1          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dcproxy_1          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dcproxy_1          | 	at java.lang.Thread.run(Thread.java:748)
dcproxy_1          | 
dcproxy_1          | Jan 30, 2019 4:30:20 PM com.sixsq.dataclay.proxy invoke
dcproxy_1          | SEVERE: error initializing DataClayWrapper: java.lang.NullPointerException
dcproxy_1          | Jan 30, 2019 4:30:20 PM com.sixsq.dataclay.proxy invoke
dcproxy_1          | SEVERE: halting service

**Comment by cjdcordeiro** [comment]
alright @fcarp10 so this is why. If the proxy is not working, CIMI won't reach the DB. 

You should confirm with @aqueralt but this is most likely an issue with the versions of DC vs DCPROXY

**Comment by cjdcordeiro** [comment]
this can now be closed with https://github.com/mF2C/dataClay/commit/11cd60f8932b35c44d47a31ebc2698dabb57588d

We are keeping the DC proxy. 

To test the DC/CIMI use these new versions: https://github.com/mF2C/cimi/blob/master/_demo/docker-compose.yml
