### ISSUE TITLE
Event system - delete

### ISSUE THREAD

**Issue by giulianacarullo** [mF2C/mF2C#111]
CIMI support for device deletion.

**Comment by cjdcordeiro** [comment]
create an event resource creation when deleting resources.

**Comment by cjdcordeiro** [comment]
new job exemplifying an event for deleted resources is in Docker image sixsq/cimi-sse:1.0.1

check the code here: 
https://github.com/cjdcordeiro/cimi-server-events/blob/master/jobs/demoDelete.py
