### ISSUE TITLE
deploy mF2C agents (with leader and backup) in the testbed

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#118]
needs #117

**Comment by ALEJANDROJ19** [comment]
Deployment of agents and leader is successful, but more testing is necessary. Right now, to make it possible, is mandatory to attach the wireless iface to the discovery container and perform some commands. We have modified the install.sh script to automate all the procedure (pending https://github.com/mF2C/ResourceManagement/issues/44 to upload new version).
 PENDING:
Leader receives "childrenIPs" and select a Backup (static right now, pending auto).

**Comment by ALEJANDROJ19** [comment]
https://github.com/mF2C/mF2C/tree/install-patch
