### ISSUE TITLE
test device registration in NB nano

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#136]
needs https://github.com/mF2C/mF2C/issues/99

**Comment by ssgUPC** [comment]
Uploaded the new version of arm image - `latest-V2.0.20-arm`

**Comment by cjdcordeiro** [comment]
same problem
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by cjdcordeiro** [comment]
problem: `"Architecture": "amd64",`

**Comment by cjdcordeiro** [comment]
waiting on https://github.com/mF2C/ResourceManagement/issues/30

**Comment by ssgUPC** [comment]
Finished the testing!! Now we can move it again to the Ready for Demo

**Comment by cjdcordeiro** [comment]
this is not working yet, as the microagent IP is not being written into the `agent` resource

**Comment by ssgUPC** [comment]
@cjdcordeiro, in case of agent side I have already tested the modified version of images, which are related to dataClay component. The new images are working with the agent (cloud, leader and normal agent), but as you know that microagent is connected with the leader (specifically with the cloud agent which is mounted in the tiscali cloud)...so to test that new images are correctly working or not, I need some help....It would be better for me those who are managing the cloud agent, which is mounted in tiscali cloud, if they modify the d-c file for that cloud agent then it would be much easier for me to test it.

**Comment by cjdcordeiro** [comment]
what are the images that need to be updated in the dashboard?

**Comment by ssgUPC** [comment]
The new images are - 

mf2c/trunk:dataclay-proxy-2.28
mf2c/trunk:dataclay-logicmodule-2.28
mf2c/trunk:dataclay-dsjava-2.28

**Comment by ssgUPC** [comment]
@cjdcordeiro please let me know whenever it is ready...so that I can start testing the microagent

**Comment by cjdcordeiro** [comment]
done

**Comment by ssgUPC** [comment]
Okay let me test it.. I'll get back to you soon.

**Comment by ssgUPC** [comment]
Tested!!! and Perfectly working....now you have the microagent's IP in the cloud-side `agent` resources.
