### ISSUE TITLE
Authenticate idKey during Agent initialisation

### ISSUE THREAD

**Issue by syc17** [mF2C/mF2C#152]
We need to securely bind a userId to the Agent being bootstrapped from the dockercompose.yml script.  The userId is currently input as an Docker environment variable to the Identity block in the dockercompose file.  A user can easily change the value and there is currently no validation of the IDString.
To fix this security hole, STFC proposes to replace the plain ID String using a signed String (JWS).  The String should be signed by the Cloud registration service, and encapsulated in a JWS.  JWS is formatted as a compact, URL-safe String. This can be put directly into the docker compose file or we put the String into a file and provide the file name as the env variable.  Identity block after loading the String would need to use the ACLib to validate the signature and the integrity of the JWS payload (the IDString)

**Comment by syc17** [comment]
I've drafted a possible solution but to ensure that it is viable, we need to get a common view on some issues.  Please look at this [document](https://docs.google.com/document/d/1sAv5xSiTPm4rYNxFdBjgT8qprTa37t56wLBnaYEQHoE/edit?usp=sharing) and add your comments and corrections

**Comment by syc17** [comment]
Comments from Cris:
userID doesn't exist. It's IDKey.
 - what's the difference between deviceID and agentID? It's the first time I'm hearing about agentID
 - the workflows are not clear to me. On the first one, the cloud reg speaks to the AC-lib...which one? Where is this ac-lib running? In the cloud as well?
    - plus, on the second workflow, the question remains, where is that ac-lib running? If it is running on the edge, how can it validate the JWS? It doesn't have any information about that IDKey's token
    - still on the 2nd workflow, why is the IDBlock speaking with the cloud? this cannot be assured. It is the CAU's job to validate that IDKey, otherwise you'll be getting the userID in your device, before it has been validated.

**Comment by syc17** [comment]
After some email exchanges, Cris said that it is not urgent and it is agreed that:
1) idKey generated by the cloud reg module will be stored by Dataclay in the User resource
2) during the Discovery, Auth & Cat flow, when the CAU-client is invoked, it will call CAU which in turns call the cloud reg module CIMI endpoint to get a the User resource using the idKey to verify if the user exists.  It is the responsibility of the cloud reg module to notify the user, saying that "You've just registered a new mF2C Agent with ID `deviceID`. If you haven't done this, then your IDKey might have been stolen. If that's the case, please contact us or click this link in order to reset your IDKey".  If the IDKey has been compromised, then the cloud reg module should re-generate an IDKey for that user, and invalidate (quarantine) all his/her mf2c agents

**Comment by syc17** [comment]
After an analysis of the identification block, I think step 2 proposed in the last comment should be amended.  Apparently the identification block after initialisation will use the idKey stored in the docker-compose file to register the device/Agent (.......this method sends the IDKey to the web service (ws) specified in the RegisterDevice class line 43 ........ The ws allocates a device ID and sends it to the requester node.....)    I would suggest that the web service (ws) before allocating a deviceID, actually validates the incoming idKey first.  This seems the most appropriate place in the workflow to do the validation.

**Comment by syc17** [comment]
@cjdcordeiro looking at the reg and id workflows (step 5) in D3.4, I still think the best place to verify idKey during agent bootstrap is during the process for getting a deviceID (see https://github.com/mF2C/mF2C/issues/152#issuecomment-488322013).   It is best to stick to the 'fail fast' best programming practice: why do unnecessary work and why create a deviceID (a potential security risk) for a rogue device if the idKey doesn't check out?

**Comment by cjdcordeiro** [comment]
you cannot assume an agent has connection to the internet. But instead has connection to a local CAU which can broker that action.

deviceID are not secret nor sensitive, thus no security risk

**Comment by syc17** [comment]
1) I think we need to consider what is the meaning of a 'local' CAU. A CAU available via the local (not the Agent's docker) network provided via the local access point? I seem to remember Sarang talked to you in IT1 that for the discovery etc. workflow to work, we need the internet.  @ALEJANDROJ19 perhaps you could help here, can we use a fixed ip on the local network for the 'local' CAU?

2) deviceID are not secret but it implies that the device is an mF2C device, and the cloud component needs to keep a record of this.

**Comment by alxjand** [comment]
This is a brief summary of the actions done to solve this issue:

As we explained in the issue 196, neither the IDKey nor any other sensitive or not sensitive information is sent to the agent as environment variable in the docker-compose file anymore. Instead of that, the IDKey is directly obtained in the agent from the cloud by the identification module using the user credentials as authentication method.

Once the user has been successfully identified, the system provides both, the IDKey and the deviceID.

The mentioned solution is implemented in the latest mf2c/identification image (v2).
