### ISSUE TITLE
Monitoring stores container start and stop times in ServiceContainerMetrics

### ISSUE THREAD

**Issue by rosogon** [mF2C/mF2C#172]
Monitoring saves the start and stop of containers running on the local device. The information is to be stored in ServiceContainerMetrics resource. When saved in Dataclay, the log can be read from the SLA in the leader to calculate the effective availability

What if the same container starts and stops several times? To be discussed.

See #171

**Comment by svoorakk** [comment]
@rosogon 
- Each time a container starts, a new service-container-metric instance is created with the start time.
- When the container stops, the service-container-metric instance is updated with the end time.
So if a container starts multiple time there will be multiple instances of service-container-metric for a given container id + device id combination.
Does that work ?

**Comment by rosogon** [comment]
Yes, I think it is the simplest and best option :)

**Comment by sandlbn** [comment]
merged, landscape 0.66 built on docker cloud https://cloud.docker.com/u/mf2c/repository/docker/mf2c/landscaper

**Comment by rosogon** [comment]
Current cimi spec is wrong: stop_time must be optional for the case where the container starts (the start must be recorded, but it obviously has not ended yet). mF2C/cimi#81 fixes this.

Check expected behavior in comment above: https://github.com/mF2C/mF2C/issues/172#issuecomment-492748557

**Comment by rosogon** [comment]
Hi @sandlbn , 

If landscaper fails when starting because of the "docker swarm not found" problem, is the piece of code of this issue being executed?
