### ISSUE TITLE
prepare testbed overview to be discussed at f2f meeting

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#20]

**Comment by ALEJANDROJ19** [comment]
Done, You can check the slides in the [OwnCloud](https://repository.atosresearch.eu/owncloud/index.php/apps/files/?dir=%2FmF2C%2FMeetings%2F06.%20Developers%27%20Day%20and%20GA%20Geneva%2030-31-1%20Jan-Feb%202018%2FDay%201#).
