### ISSUE TITLE
test release 1.0.1 and report all bugs encountered

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#200]
document: https://github.com/mF2C/mF2C/blob/master/docs/mf2c_agent.md

**Comment by fcarp10** [comment]
I created new release 1.0.1 with an updated version of resource categorization that fixes random failures of the hello-world. Now, hello-world only fails when is executed too fast after the agent is started. If it fails, execute it again later until all tests pass. **Only tested on standalone Linux and Mac**.

**Comment by cjdcordeiro** [comment]
@fcarp10 can you pass around a shared document where we an gather all inputs

**Comment by cjdcordeiro** [comment]
document: https://github.com/mF2C/mF2C/blob/master/docs/mf2c_agent.md

**Comment by robbeng** [comment]
Updated https://github.com/mF2C/mF2C/blob/master/docs/mf2c_agent.md with test reports on agent version PR #204
