### ISSUE TITLE
Multi-agent tests

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#211]

**Comment by fcarp10** [comment]
@ssgUPC In the testbed `device-dynamic` is never submitted. 

`landscaper_1               | [2019-07-11 14:09:31 UTC] [INFO] : CIMI Connection OK. Devices returned: 1 
landscaper_1               | [2019-07-11 14:09:31 UTC] [INFO] : Received non empty devices list from CIMI 
landscaper_1               | [2019-07-11 14:09:31 UTC] [ERROR] : Dynamic data has not been set for this device: device/01d48910-ad74-4763-abc7-8c77983326f0. No dynamic file will be saved. 
landscaper_1               | [2019-07-11 14:09:31 UTC] [ERROR] : General Error hwloc/cpuinfo for device: device/01d48910-ad74-4763-abc7-8c77983326f0 - Error message: 'NoneType' object has no attribute 'get' 
landscaper_1               | [2019-07-11 14:09:31 UTC] [INFO] : Adding physical machines to the landscape... `

` [ResourceCategorization]  FAILED: no device dynamic was added 
 [SLAManager]     SUCCESS: service "sla-template/4652ef57-bf58-41b6-b88e-080bfe0348e0" created successfully 
 [ServiceManager]  SUCCESS: service "service/abdff7f7-f4f3-49a8-b091-56ed3c1989c3" created successfully 
 [Analytics]      FAILED: failed to return list of ip addresses 
jq: error (at <stdin>:0): Cannot iterate over null (null)
 [LifecycleManager]  FAILED: failed to launch service instance 
 [HelloWorldTest]  FAILED: ip address from service instance [] does not match with ip from analytics [null] 
`

**Comment by ssgUPC** [comment]
@fcarp10 can you please provide me the log of my container?

**Comment by fcarp10** [comment]
I don't have them, but you can get it by deploying the agent in the testbed.

**Comment by ssgUPC** [comment]
Okay, @fcarp10 please give me some times/days...I'll get back to you soon...

**Comment by cjdcordeiro** [comment]
@rsucasas to test with 2 children
