### ISSUE TITLE
add the vpn client as a permanent microservice for mf2c

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#216]

**Comment by jjensenral** [comment]
The only tricky bit is how to advertise the IP address to an outside caller.
Would it be acceptable to call the container with `docker exec -t vpn_vpnclient_1 ifconfig tun0|grep 'inet addr'|sed 's/^.*:\(.*\) .*$/\1/'` or somesuch.
Seems silly to set up an extra service specifically to return the IP address. Also, the IP address is only available after the client has finished establishing the connection.

**Comment by cjdcordeiro** [comment]
either that or simply put a Flask rest api up, with a single endpoint `/api/my-vpn-ip`

ultimately you can also use a dirq kind of approach, and write the ip into a volume where other can mount and read.

up to you

**Comment by jjensenral** [comment]
OK, cool.  For the short term, then, I will add vpnclient to the d-c as it is, and others can use the admittedly ugly command. However, I will leave also this issue open in order to implement one of the less ugly options.
