### ISSUE TITLE
the vpnserver service does not exist

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#219]
https://github.com/mF2C/mF2C/blob/master/docker-compose/docker-compose.yml#L313

**Comment by jjensenral** [comment]
The vpnserver runs in the cloud. However, the agent looks us the `vpnserver` name, so when you start the agent, you need to give the client container `--add-host vpnserver:<ip>` where `<ip>` is the address of the cloud server

**Comment by jjensenral** [comment]
Absent a cloud, I started a vpnserver manually on 213.205.14.13 as follows (as per its d-c.yml file):
`docker volume create vpnconfig`
`docker run --cap-add=NET_ADMIN -d --name vpnserver -e TRUSTCA=https://213.205.14.13:54443/certauths/rest/it2trustedca -p 1194:1194/udp -v vpnconfig:/etc/openvpn mf2c/vpnserver:latest`

**Comment by jjensenral** [comment]
confirmed that it is working.  Note that clients need `--add-host vpnserver:213.205.14.13`
