### ISSUE TITLE
Trust anchor distribution

### ISSUE THREAD

**Issue by jjensenral** [mF2C/mF2C#236]
In the absence of a trust anchor (=CA certificate) distribution mechanism, we have currently checked CA certificates into git and hardwired CA certificates into our images and scripts. This is not a security risk because certificates contain only public keys, but it makes it impossible to reuse mF2C images directly by someone who does not have access to the same CAs' private keys.

**Comment by syc17** [comment]
The credentials are in OwnClouds' WP5 credential folder.  Log in and you see all the certs and keys.  Further instructions in https://github.com/mF2C/certauth README.md
Ideally, we should have an endpoint that publish the CA's public key.  We could put this down as a not so urgent task.

**Comment by jjensenral** [comment]
Indeed: the problem is the one you have identified here: "Install [..] the public keys of the issuing CA. You also need to add the issuing CA public key to the CAU client." There are several options. Logging into owncloud to get certificates requires a person configuring, which is not compatible with the `d-c up` philosophy. Normally people use RPM/DEB repositories to distribute CA certificates and configure the `d-c` with the endpoint. Something more official like TAMP (RFC 5934) would be overkill for our environment... we need to discuss the best options. But not the most urgent task right now.

**Comment by syc17** [comment]
I have added a HTTP Get CA pem operation to the CA service.  Just need to test this now.  The idea is that you do a HTTP Get on the CA endpoint, and it returns the CA's x509 pem.

**Comment by syc17** [comment]
I have deployed the updated service.  You can do a curl to test it:  curl -kv https://213.205.14.13:54443/certauths/rest/it2untrustedca
