### ISSUE TITLE
fix identification integration tests

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#272]
https://github.com/mF2C/mF2C/blob/master/docker-compose/tests/identification-FullAgent.sh#L30 .  (you cannot register a device more than once)

and 

https://github.com/mF2C/mF2C/blob/master/docker-compose/tests/identification-FullAgent.sh#L40

and also the isolated tests, are deploying a new container. This is not needed. You must use the one already deployed as part of the agent (you can keep the isolated tests as a unit test)

**Comment by alxjand** [comment]
Both issues described here are solved in the updated identification.sh file.
