### ISSUE TITLE
replace recommender with mock container that provides list of children IPs from the Agent resource

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#275]
@rsucasas what do you expect, and which call are you doing

@ALEJANDROJ19 @fcarp10 implmenet basic alpine container that goes through Agent resources and returns the expected output, on the same API call endpoint

**Comment by rsucasas** [comment]
**what do you expect, and which call are you doing**

- call to recommender: `POST http://analytics-engine:46020/mf2c/optimal`

- response from recommender: `[{"ipaddress":"192.168.1.50"}, {"ipaddress":"192.168.1.51"}, {"ipaddress":"192.168.1.52"}]`

**Comment by ALEJANDROJ19** [comment]
Done and PR accepted into master with mock component. Tested with hello-world and integration tests by @fcarp10 at mF2C meeting.
