### ISSUE TITLE
Filter devices by sensors and agentType that are required for the service

### ISSUE THREAD

**Issue by fcarp10** [mF2C/mF2C#322]

**Comment by ALEJANDROJ19** [comment]
@ssgUPC to provide an example of the environment variables for sensors and actuators

**Comment by fcarp10** [comment]
This is an example of a service
{
         "name": "compss-hello-world",
         "description": "hello world example",
         "exec": "mf2c/compss-test:it2",
         "exec_type": "compss",
         "exec_ports": [8080, 8081],
         "agent_type": "normal",
         "num_agents": 1,
         "cpu_arch": "x86-64",
         "os": "linux",
         "cpu": 0.0,
         "memory": 0.0,
         "disk": 0.0,
         "network": 0.0,
         "storage_min": 0,
         "req_resource": ["sensor_1"],
         "opt_resource": ["sensor_2"]
    }

**Comment by ssgUPC** [comment]
@sandlbn Please follow a couple of tickets no in the "Done" section #53, #56, #57 and #115

**Comment by sandlbn** [comment]
I do believe we can close this one?

**Comment by ssgUPC** [comment]
Yes yes!!!

**Comment by rsucasas** [comment]
solved
