### ISSUE TITLE
Enable Subject Alternate Names on CA and test extensively

### ISSUE THREAD

**Issue by cketley** [mF2C/mF2C#39]
Pau and Alejandro J have found that the CN on the certificate is limited to 64 characters (confirmed by a test). However the CAU client subsystem requires to use a name that is much larger.

Enable Subject Alternate Names in the CAs.

But note this interacts with browsers validating certificates and software libraries validation of certificates.
Test against all major browsers including a few of the older versions. Test against OpenSSL, BouncyCastle, Java Security Architecture, Operating systems eg Android, Linux.

**Comment by syc17** [comment]
Obsolete.  In the BCN F2F meetng in Jan2019, UPC said they are truncating the deviceId from 128 to 64 bits to make it fit with the CN length.  UPC said they have no further plan of using the certificate DN or CN for any meaningful operations.  So there is no point in pursuing the issue.
