### ISSUE TITLE
prototype the event service

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#50]
STFC and INTEL together should come up with a plan and first prototype for the event service

**Comment by cketley** [comment]
We have built MQTT into the agent controller security library, so that would be a good transport for events - we don't want to lose events or have them arriving more than once...

**Comment by syc17** [comment]
You can also add transaction watcher on blockchain to monitor events.  But we should find out what INTEL want first.

**Comment by syc17** [comment]
I understand that Alex wants to have notification on new members joining the Fog.  Could he elaborate on:
1. who exactly needs the notification,  landscaper??
2. how does he want to be notified (pub/sub like mqtt, http via landscaper endpoint???? ) 
3.  what info are needed (e.g. ip, device-id,…..???)  
4. is notification required on agent dropping out?
Thanks

**Comment by cjdcordeiro** [comment]
@aleckey @giulianacarullo  ⬆️

**Comment by cjdcordeiro** [comment]
need to discuss with @aleckey whether the technical implementation of the subscription to the notification service is feasible

**Comment by cjdcordeiro** [comment]
@aleckey @guilianacarullo please provide feedback

**Comment by cjdcordeiro** [comment]
here’s the 1st version of the event service: https://github.com/mF2C/cimi-server-events

it has also been added to the compose file, with a default channel `demo`, which sends out events everytime a new user is added
