### ISSUE TITLE
automation of the agent installation and initialization

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#51]
all of the pre and pos-installation steps regarding system configuration and definition of environment variables should either be removed or somehow automated, in such a way that users only need to :
 1. Download the mf2c app
 2. Run the executable

connected to #78

**Comment by ALEJANDROJ19** [comment]
Regarding the Policies block, the Allowed Backup list only defines the elective devices that the Leader can select as backup. This step is not necessary in a normal agent that enters into the system unless the user wants to test the Leader Protection in the scenario, what seems fair to add some manual steps for that purpose (at least for this moment).

**Comment by cjdcordeiro** [comment]
so if the allowed backup is not passed, how is the backup agent elected?

**Comment by ALEJANDROJ19** [comment]
@cjdcordeiro At this moment, if the allowed list is empty, no backup is selected.

**Comment by cjdcordeiro** [comment]
and if the backup is not selected, and the leader goes down? what happens?

**Comment by ALEJANDROJ19** [comment]
If no backup is selected, there is no agent watching for the leader status, so the control of the area is lost.

**Comment by cjdcordeiro** [comment]
alright so that's the missing feature. Is anyone working on that? Who's in charge?

**Comment by ALEJANDROJ19** [comment]
Some other features are required to implement this one (like the topology automatically set in a CIMI resource) so no prevision at this moment.
