### ISSUE TITLE
A way to provide service/COMPSs job results and status to calling clients

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#59]
An mF2C service's developer can create COMPSs jobs, then register and run them via the lifecycle component. This is also true for docker/dcompose services, but let's just focus on COMPSs jobs.

Once the job is submitted---and, to prevent misunderstandings, this means executing e.g. Java code that a developer has written in the COMPSs framework---one currently has no way of interfacing with the job. Developers are somewhat expected to provide or create their own result distribution framework. This is something mF2C as a framework should provide.

During the runtime of the service, and after it, there should exist an API call to either lifecycle, cimi or another service, whichever is deemed the proper way to interface with mF2C, with which a developer can qeury the status of the submitted job. Even basic statuses would be fine, e.g. created, running and finished.

Once a job is done, results need to be extracted from it in order to use them. In UC2, we currently access and insert results into the (local) application database directly, which is not desired in distributed systems. As we have submitted the job via a lifecycle endpoint, one would expect to have results available, on completion, at another endpoint of the same or related service.

The challenges for this are that, theoretically, the lifecycle component can start the job in a completely unrelated node where no components of an _mF2C application_ are even running. The system would thus need to support the efficient transfer of results to the request-initiating node. All details should be abstracted away from the developer via API calls to a service.

Another challenge is the storage of results - how long are they stored for? With what priority compared to other results? In the not-unlikely event that the node containing the result suffers from sudden destruction or perhaps just a loss of connectivity, will the computation data be stored redundantly? What would this redundancy entail with regards to being resilient to different magnitudes of network graph cuts? Would the computation be repeated? Would all this be configurable?

**Comment by cankarm** [comment]
@sstanovnik please review and revise the description of the issue.

**Comment by sstanovnik** [comment]
@cankarm I've rewriten the issue description to what I believe are the main goals and concerns with regard to this topic.

**Comment by cjdcordeiro** [comment]
@sstanovnik please write down the results from the f2f meeting and move the ticket into "READY FOR DEMO"

**Comment by sstanovnik** [comment]
What we found was that this will not be _difficult_ to implement, but will require some coordination between COMPSs and lifecycle:

The request from a client's point of view:

 - as a prerequisite, an mF2C COMPSs service will be deployed through the lifecycle manager
 - a client will submit a new job to the lifecycle manager on the existing endpoint, which will return a _job identifier_
 - another endpoint on the lifecycle manager will be available that will enable checking whether the job with a previously obtained identifier has finished and facilitate getting back the results - this is through the HTTP call, not directly through dataClay or similar
 - as a future feature, if/when the notification system is implemented, the client will be notified of the job's completion through it so this will change from a poll-based to an interrupt-based feature

The technical details in the background:

 - COMPSs and lifecycle need to communicate a job's status between them
 - the result of the computation will be stored in dataClay, but this _will be completely transparent to the client_
 - to facilitate result storage, all results will have to be serialised into byte arrays _by the client_ - this serialised value will then be transferred when the client requests the result
   - this puts the burden of serialisation on the client, but makes storing results in dataClay simple (or maybe even possible) as there will only be one "result type"; we cannot avoid serialisation either way as we need to transfer the data over the network
