### ISSUE TITLE
Proposal for integrating CIMI with MQ

### ISSUE THREAD

**Issue by jjensenral** [mF2C/mF2C#70]
required by https://github.com/mF2C/mF2C/issues/50

Intel needs subscription to events such as resource added/removed. It is proposed to embed message queue functionality into the CIMI service.
STFC earlier piloted a F2C infrastructure based on Mosquitto which may be useful

**Comment by cjdcordeiro** [comment]
waiting on the requirements from @aleckey

**Comment by cjdcordeiro** [comment]
a first proposal and prototype have been provided. The suitability of the solution is currently being evaluated by Intel
