### ISSUE TITLE
improve website experience

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#74]
the Google audit returns the following values, which could be improved:
<img width="657" alt="screen shot 2018-09-05 at 1 35 03 pm" src="https://user-images.githubusercontent.com/4047767/45090809-b5a6ca00-b110-11e8-8c98-444bb1d55dc4.png">

**Comment by cjdcordeiro** [comment]
<img width="927" alt="screen shot 2019-01-16 at 3 29 53 pm" src="https://user-images.githubusercontent.com/4047767/51255474-9f085d80-19a3-11e9-9296-0302bf3ad7ad.png">

**Comment by robbeng** [comment]
![screenshot--2019 02 15-16-31-29](https://user-images.githubusercontent.com/34238140/52866666-78267e00-313f-11e9-8891-3de7c29f86de.png)

Values have been improved, the ticket can be closed
