### ISSUE TITLE
[event service] define criteria for the desired events

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#75]
come up with a list of requirements, including which are the types of events we are interested on having. 

needed by #70

**Comment by cjdcordeiro** [comment]
by @aleckey:

```
Initial requirements for the Event management system. Not sure what level of detail required. While I am only interested in Device and Service_Instance objects, you could probably standardize this for any specified CIMI object.

 

I don’t have a requirement for an UPDATE event, where some property(s) of the object is updated

 

- Device:

Every time a device object is added or removed from CIMI, raise a DEVICE_ADDED | DEVICE_REMOVED event with device_id as body

 

- Service_Instance:

Every time a service_instance object is added or removed from CIMI, raise a SERVICE_INSTANCE_ADDED | SERVICE_INSTANCE_REMOVED event with service_instance_id as body

```

**Comment by FranCarpio** [comment]
Do you really mean service instance? or you mean when a new service is registered into the system?

**Comment by cjdcordeiro** [comment]
@aleckey ⬆️ 

also, @aleckey , these criteria is fine for the CIMI notification server...we just need to know whether you are fine with using SSE instead of websockets

**Comment by cjdcordeiro** [comment]
in theory it should be fine

**Comment by rosogon** [comment]
For SLA, it makes sense to send violations to event service. F.e., to perform adaptation if things are going wrong. The interested listener would be LM (at least).
