### ISSUE TITLE
define workflow for the trusted client requests

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#76]
- which certificate does the client use?
 - who issues it?
 - where does it sit in the agent?
 - how can the components use it in a request?
 - how does the recipient interface considers and trusts it?

**Comment by cjdcordeiro** [comment]
more info at https://docs.google.com/document/d/1xvsUaHbJUTqFqJG40ThazP4rhNmo8wN5SJFwYa_kA4w/edit?usp=sharing

**Comment by syc17** [comment]
Proposed flow @ 
https://docs.google.com/document/d/1h9CC5fT8vvbYO_iOUiOY7-f4Mf8RgW031nBUuw_HgjA/edit?usp=sharing

**Comment by cjdcordeiro** [comment]
AP schedule a topic specific call before the release cycle

**Comment by jjensenral** [comment]
Following the discussion a couple of weeks ago, there are three things to secure: CIMI, Dataclay, and COMPSs. These proposals are now documented in D4.2.
