### ISSUE TITLE
decide which components can be merged

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#79]

**Comment by rsucasas** [comment]
If needed, the Lifecycle and User Management modules can easily be merged in one docker image. Both are python applications.

**Comment by cjdcordeiro** [comment]
@alexbarcelo you told me you were doing something wrt dataclay. Can you please put the specifics in this ticket?

**Comment by aleckey** [comment]
We are in process of removing the InfluxDB being used by the AnalyticsEngine module. However, as the telemetry is Timeseries data, it would difficult to remove InfluxDB from the Monitoring. I can discuss on Developer call

**Comment by cjdcordeiro** [comment]
@aleckey thanks. please do. I won't be there but feel free to discuss it.
