### ISSUE TITLE
create workflow for a cloud-specific deployment

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#82]

**Comment by aqueralt** [comment]
The current implementation of the lifecycle is in D5.1-Fig. 19. 
What I think we need to do is a combination between this workflow and our first definition of the lifecyle in D4.3-Fig. 3. Here the concept of "going up" was considered in general when the appropriate reosurces were not found in the current cluster. The cloud-specific case is a particular case of this, by somehow requiring cloud in the initial "recipe" created when adding the service to the catalog.

**Comment by rsucasas** [comment]
Which component should the Lifecycle call to know who is the agent's parent? This is needed to update / create this workflow.

**Comment by cjdcordeiro** [comment]
I guess the recommender...

**Comment by cjdcordeiro** [comment]
@aqueralt do you have the original raw file that I can edit?

**Comment by aqueralt** [comment]
The lifecycle diagram in D4.3 is here: https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FmF2C%2FWorking%20Folders%2FWP4%20mF2C%20Gearbox%20block%20design%2FWP4%20Workflows%2FD4.3%20workflows

I don't have the updated version for D5.1, maybe @rsucasas can provide it.

**Comment by rsucasas** [comment]
I just uploaded the last version used in D5.1. It can be found here:

https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FmF2C%2FWorking%20Folders%2FWP5%20PoC%20integration%2FT5.1%2Flm-diagrams

I think, that apart from the call to the parent, there are a few things that need to be updated. For example, if we finally are going to call docker api directly from the Lifecycle, instead of calling the lifecycle to deploy a service.

**Comment by rsucasas** [comment]
I will try to have a new version of this workflow ready for this Wednesday, ok?

**Comment by cjdcordeiro** [comment]
👍 I can help if you need

**Comment by rsucasas** [comment]
I uploaded a new version to the same folder. The sequence changed a bit. Now I check twice if there are available agents to deploy the service instance. One after getting the results (list of agents) from the recommender (if there are no agents then I forward the request to the parent). And then after checking the resulting list of agents with the qos provider and the sharing model / profile. Here again, if I get a list of agents from the recommender, but then these agents can not run the service, then I forward the request to the parent.

**Comment by cjdcordeiro** [comment]
makes sense. I'm not sure whether it is the recommender that should tell you who you parent it. The recommender recommends a location to run your service. If it cannot recommend one, it will just return `False` or an empty list...whatever...the point is that the LM should then either ask someone else for his parent, or even check directly in CIMI

**Comment by rsucasas** [comment]
workflow updated:

![Lifecycle Manager_ Service initialization_v2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e9c05c42669c0014ad42bf/125516c66e82c728ace21e0d46c49d9c26819aaa83ecff6ea553f1932c5418331a01b13d7986e668b64c7215060e12f50b091b1da3a7e66da4a42062ca1e54b7843e1b66cc2f14a5ecd14de902b328da4e86e7b48a4cc6eb3b76b1d98f1d2c02175ad8a1096afdc0019d1ae441f34c52ae123360ef7e337a469d1d7c2469756b.png)

https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FmF2C%2FWorking%20Folders%2FWP5%20PoC%20integration%2FT5.1%2Flm-diagrams

**Comment by aqueralt** [comment]
Hi, 
I think this new version is fine. Maybe in the future we can replace the call to Discovery by a get from CIMI, if Discovery stores it there.

**Comment by cjdcordeiro** [comment]
in fact, @rsucasas , if you query cimi like this: `curl -XGET https://cimi/api/device-dynamic ....` you'll get a JSON where you have an attribute called `myLeaderID`. This is supposed to be defined by the resource categorizer (from @ssgUPC)
