### ISSUE TITLE
Define format for computation results

### ISSUE THREAD

**Issue by aqueralt** [mF2C/mF2C#84]
Define CIMI resource to manage the results of COMPSs computation to be returned to apps

**Comment by sstanovnik** [comment]
Does this have to be an actual clojure definition for the internal workings or are we talking about the contract for the format of data that will be returned through the HTTP interface of the lifecycle manager?

For the latter, my proposal is this:

```javascript
// 2xx response: 
{
    "compute_node_id": "UUID of the (main) node that controlled the computation",
    "computed_at": "<ISO 8061 timestamp of the computation finish time>",
    "data": "<base64 encoded serialized dump>"
}

// 4xx/500 response:
{
    "error": "error message"
}
```

I wouldn't complicate things by doing anything fancier than base64 or even BSON. We'll have a separate endpoint for checking whether the job succeeded, but for safety, one error type should be "result not available". 

This is just the outside interface to the LM. Do we also need to define the programming interface for COMPSs tasks to return results "properly"?

**Comment by cankarm** [comment]
Great proposal, 
do we need something like:
- ID of parent application or the specific (sub)application task that requested a job? Could be beneficial when some disaster occur in the fog area (leader disappears for some time) and system needs to recreate the state at that point, without restarting all computations again. 
- or UUID of the job - this would be as a ticket that LM returns to the application when the job is accepted and put in a queue for execution.

**Comment by sstanovnik** [comment]
Great ideas. I am not completely sure if we can get the ID of the requesting application---does this information even exist?

Here's the modified version, with the requesting application ID, which can be omitted if it is not feasible:

```javascript
// 2xx response, v2: 
{
    "requesting_application_id": "<identifier of the application that submitted the job>",
    "compute_node_id": "<UUID of the (main) node that controlled the computation>",
    "computation_id": "<job identifier, same as the one from the submission>",
    "computed_at": "<ISO 8061 timestamp of the computation finish time>",
    "data": "<base64 encoded serialized dump>"
}
```

**Comment by cjdcordeiro** [comment]
finish this discussion in Barcelona at the F2F meeting (Feb 2019)

**Comment by cankarm** [comment]
In Barcelona we:
* confirmed the content of the response
* confirmed the path of response (COMPSs -> Lifecycle -> Application)
* agreed that no notifications will be supported for first step, just pull 
* agreed that notifications (if they will be developed) are just an update of the previous version

@cjdcordeiro : what criteria should be met to finalize this task?

**Comment by cjdcordeiro** [comment]
I guess you should create technical tickets to address each one of these bullets, and add a workflow for this, that needs to be validated once the tickets are finalized

Then this task can be closed and continued in the new tickets

**Comment by sstanovnik** [comment]
All that is left here is to define the CIMI resource with the definition in my previous comment in this thread. Other issues are #85, #86, #87 and #88.

I've created #124 which depends on this issue and all of the above to have a validation task.
