### ISSUE TITLE
fix CA

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#96]

**Comment by syc17** [comment]
Vanilla CA Rest Services deployed at the Engineering machine (148.62.113.142:8080).  Code and documentation available from https://github.com/mF2C/certauth.git    See the src/main/resources/vanilla-ca-howto.pdf on how to use the services and the endpoints.  The Junit provides example code in JAVA on how to interact with the REST application.  A python client is forthcoming.

**Comment by syc17** [comment]
provided python client example in src\main\resources and updated how-to document.
